services:
  mcp:
    build: .
    env_file:
      - .env
    ports:
      - "8810:8000"
    volumes:
      - /home/ubuntu/ms-playwright:/root/.cache/ms-playwright
      - /usr/share/py-projects/next-train-mcp/data:/app/data